import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import GitHubCorner from '@/components/GitHubCorner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nextjs 14 Template Password Protected',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GitHubCorner />
        <div id="glare"></div>
        {children}
      </body>
    </html>
  )
}
